name: Dezination
favicon: null
layout_spectrum: 0.01065175305120647
typography_spectrum: 0.6305309541057795
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5622066147625446
  lightness: 0.1618256054352969
  saturation: 0.08371621021069586
  rhythmicContrast: 0.6727824823465198
purpose: []
